export enum DocURL {
  COOKIE_POLICY = 'https://docs.marsprotocol.io/docs/overview/legal/cookie-policy',
  COUNCIL = 'https://council.marsprotocol.io',
  COUNCIL_LEAP = 'https://cosmos.leapwallet.io/chains/mars/governance',
  COUNCIL_STATION = 'https://station.terra.money/gov#PROPOSAL_STATUS_VOTING_PERIOD',
  COUNCIL_TESTNET = 'https://testnet.keplr.app/chains/mars-hub-testnet',
  COUNCIL_KEPLR = 'https://wallet.keplr.app/chains/mars-hub',
  FIELDS = 'https://docs.marsprotocol.io/docs/learn/rover/rover-intro',
  LANDING = 'https://docs.marsprotocol.io/',
  PRIVACY_POLICY = 'https://docs.marsprotocol.io/docs/overview/legal/privacy-policy',
  RED_BANK = 'https://docs.marsprotocol.io/docs/learn/red-bank/red-bank-intro',
  RED_BANK_LIQUIDATIONS = 'https://docs.marsprotocol.io/docs/learn/red-bank/red-bank-liquidations',
  SECURITY = 'https://docs.marsprotocol.io/docs/overview/security/audits',
  TERMS_OF_SERVICE = 'https://docs.marsprotocol.io/docs/overview/legal/terms-of-service',
  UNLOCK_POSITION = 'https://docs.marsprotocol.io/docs/learn/workstation/vaults/unlocking',
}
