export enum QUERY_KEYS {
  BLOCK_HEIGHT = 'blockHeight',
  MARS_BALANCE = 'marsBalance',
  MARS_ORACLE = 'marsOracle',
  MARS_PRICE = 'marsPrice',
  REDBANK = 'redbank',
  USER_BALANCE = 'userBalance',
  USER_DEBT = 'userDebt',
  USER_DEPOSIT = 'userDeposits',
  USER_ICNS = 'userIcns',
  ATOM_PRICE = 'atomPrice',
  SAFETY_FUND_BALANCE = 'safetyFundBalance',
  MARKET_DEPOSITS = 'marketDeposits',
  USE_LP_TOKEN = 'useLpToken',
  ESTIMATE_FEE = 'estimateFee',
  ESTIMATE_FARM_FEE = 'estimateFarmFee',
  PROVIDE_LIQUIDITY = 'provideLiquidity',
  UNLOCK_MESSAGE = 'unlockMessage',
}
